# Generated by Django 3.2.4 on 2021-10-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211014_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activation_key_expires',
            new_name='activation_key_created',
        ),
    ]
